apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}
  labels:
    app: {{ include "myapp-chart.name" . }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.dotnet.port }}
      targetPort: {{ .Values.dotnet.port }}
      protocol: TCP
      name: dotnet
  selector:
    app: {{ include "myapp-chart.name" . }}
