name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-image:latest .

    - name: Tag Docker image
      run: |
        docker tag my-image:latest my-image:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push my-image:latest
        docker push my-image:${{ github.sha }}
